"""The derived fault-capable model version (deviation D8).

The file under ``resources/modelica/`` is generated by ``scripts/derive_faultcapable.py``.
These tests read it back with the project's own Modelica parser and assert the four changes
the derivation promises — so an upstream change, or an edit of the derivation, cannot quietly
alter what the AAS attaches and the simulation runs.
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path
from typing import Any

import pytest

from aas_fluid_twin import config
from aas_fluid_twin.benchmark.modelica import ModelicaModel, load_modelica_model
from aas_fluid_twin.simulation.runner import PARAMETER_TARGETS

pytestmark = pytest.mark.benchmark_data

#: The handles, with the value that means "nominal plant".
NOMINAL_DEFAULTS = {
    "V212_opening": 1.0,
    "V211_opening": 0.0,
    "V210_opening": 0.0,
    "V211_return_to_B201": False,
}


def _derive_module() -> Any:
    path = Path(__file__).resolve().parents[1] / "scripts" / "derive_faultcapable.py"
    spec = importlib.util.spec_from_file_location("derive_faultcapable", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules["derive_faultcapable"] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def faultcapable() -> ModelicaModel:
    if not config.FAULTCAPABLE_MODEL_FILE.is_file():
        pytest.skip("run scripts/derive_faultcapable.py first")
    return load_modelica_model(config.FAULTCAPABLE_MODEL_FILE)


def test_checked_in_file_is_what_the_script_derives() -> None:
    if not config.MODELICA_FILE.is_file():
        pytest.skip("benchmark data absent")
    module = _derive_module()
    derived = module.derive(config.MODELICA_FILE.read_text(encoding="utf-8"))
    assert derived == config.FAULTCAPABLE_MODEL_FILE.read_text(
        encoding="utf-8"
    ), "the checked-in ModVA_faultcapable.mo is stale — rerun scripts/derive_faultcapable.py"


def test_model_is_a_separate_version_not_a_patch_of_the_original(
    faultcapable: ModelicaModel,
) -> None:
    upstream = load_modelica_model()
    assert faultcapable.name == "ModVA_faultcapable"
    assert upstream.name == "ModVA_online_stable"
    assert faultcapable.experiment == upstream.experiment
    assert faultcapable.actuator_table == upstream.actuator_table


def test_clogging_handle_replaces_the_pinned_valve(faultcapable: ModelicaModel) -> None:
    assert "V212" in faultcapable.declarations
    assert "V207" not in faultcapable.declarations
    assert ("V212", "opening") not in {(c.first, c.second) for c in faultcapable.connections}
    # V212 keeps the throttle's own pressure drop, not a generic valve's.
    upstream = load_modelica_model()
    assert (
        faultcapable.declarations["V212"].modifiers["dp_nominal"]
        == upstream.declarations["V207"].modifiers["dp_nominal"]
    )


def test_leak_path_and_its_two_destinations_exist(faultcapable: ModelicaModel) -> None:
    for component in ("Tee4", "V211", "Junction_V211", "V211_to_X203", "V211_to_B201", "X203"):
        assert component in faultcapable.declarations, component
    neighbours = faultcapable.neighbours("V211")
    assert "pipe_Tee4_V211" in neighbours and "Junction_V211" in neighbours
    # the riser is split, so FI271 no longer reaches B204 directly
    pairs = {(c.first, c.second) for c in faultcapable.connections}
    assert ("FI271.port_b", "pipe_FI271_Tee4.port_a") in pairs
    assert ("pipe_FI271_B204.port_b", "tank_B204.topPorts[1]") not in pairs
    assert "X203.ports[1]" in {c.second for c in faultcapable.connections}
    assert "tank_B201.topPorts[2]" in {c.second for c in faultcapable.connections}


def test_crossover_joins_the_suction_manifold_to_the_pump_inlet(
    faultcapable: ModelicaModel,
) -> None:
    for component in ("Tee3", "Tee5", "V210", "pipe_Tee3_V210", "pipe_V210_Tee5"):
        assert component in faultcapable.declarations, component
    assert set(faultcapable.neighbours("V210")) == {"pipe_Tee3_V210", "pipe_V210_Tee5"}


def test_temperature_sensors_match_their_tags(faultcapable: ModelicaModel) -> None:
    """Deviation D4: upstream has TI261 in B204 and TI262 at the manifold — swapped."""
    upstream = load_modelica_model()
    assert set(upstream.neighbours("TI261")) == {"Pipe_B204_V207"}
    assert set(upstream.neighbours("TI262")) == {"pipe_V203_Tee2"}
    assert set(faultcapable.neighbours("TI261")) == {"pipe_Tee3_Tee2"}  # suction manifold
    assert set(faultcapable.neighbours("TI262")) == {"Pipe_B204_V207"}  # B204


@pytest.mark.parametrize(("handle", "nominal"), sorted(NOMINAL_DEFAULTS.items()))
def test_every_handle_defaults_to_the_nominal_plant(handle: str, nominal: float | bool) -> None:
    source = config.FAULTCAPABLE_MODEL_FILE.read_text(encoding="utf-8")
    match = re.search(
        rf"parameter\s+(?:Real|Boolean)\s+{handle}\s*(?:\([^)]*\))?\s*=\s*(?P<value>[\w.]+)",
        source,
    )
    assert match is not None, f"{handle} is not declared as a parameter"
    expected = str(nominal).lower() if isinstance(nominal, bool) else str(int(nominal))
    assert match["value"] == expected


def test_the_runner_addresses_exactly_these_handles() -> None:
    """``PARAMETER_TARGETS`` maps AAS idShorts onto Modelica names; for the handles they match."""
    for handle in NOMINAL_DEFAULTS:
        assert PARAMETER_TARGETS[handle] == handle
