server.port=8081
spring.application.name=ModVA AAS Discovery Service
basyx.aasdiscoveryservice.name=modva-aas-discovery
basyx.backend=InMemory
basyx.cors.allowed-origins=*
basyx.cors.allowed-methods=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
